name: Android Debug CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apks
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload Customized Notification
        uses: actions/upload-artifact@v2
        with:
          name: customized-notification
          path: customized-notification/build/outputs/apk/debug/customized-notification-debug.apk

      - name: Upload MyCanva
        uses: actions/upload-artifact@v2
        with:
          name: mycanva
          path: mycanva/build/outputs/apk/debug/mycanva-debug.apk

      - name: Upload ShortStory
        uses: actions/upload-artifact@v2
        with:
          name: short-story
          path: short-story/build/outputs/apk/debug/short-story-debug.apk

      - name: Upload Maps
        uses: actions/upload-artifact@v2
        with:
          name: maps
          path: maps/build/outputs/apk/debug/maps-debug.apk

      - name: Upload Geofence
        uses: actions/upload-artifact@v2
        with:
          name: geofence
          path: geofence/build/outputs/apk/debug/geofence-debug.apk
