name: Android Debug CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload Customized Notification APK
        uses: actions/upload-artifact@v1
        with:
          name: customized-notification
          path: customized-notification/build/outputs/apk/debug/customized-notification-debug.apk
      - name: Upload MyCanva APK
        uses: actions/upload-artifact@v1
        with:
          name: mycanva
          path: mycanva/build/outputs/apk/debug/mycanva-debug.apk
      - name: Upload ShortStory APK
        uses: actions/upload-artifact@v1
        with:
          name: short-story
          path: short-story/build/outputs/apk/debug/short-story-debug.apk
